# Generated by Django 5.2.14 on 2026-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prefered_roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="prefered_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_profiles",
                to="profile.prefered_roles",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="candidate_profiles", to="profile.skill"
            ),
        ),
    ]
