# Generated by Django 5.2.14 on 2026-06-15 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "profile",
            "0002_prefered_roles_skill_candidateprofile_prefered_roles_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="Skills",
        ),
    ]
