# Generated by Django 5.2.14 on 2026-06-07 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified_at",
        ),
    ]
