# Generated by Django 5.2.14 on 2026-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_user_id_alter_user_email_candidateprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CandidateProfile"),

        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),

        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
