# Generated by Django 5.2.14 on 2026-06-14 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_candidateprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CandidateProfile",
        ),
    ]
